name: sandbox_feature
description: "A sandbox feature isolated from [sandbox] and [sandboxed] packages."
resolution: workspace
publish_to: none
version: 1.1.0

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  sandboxed_core: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

