name: ui_kit
description: "A new Flutter package project."
version: 0.1.0

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  sandboxed_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

