name: ui_kit
description: "A new Flutter package project."
resolution: workspace
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.9.0
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  sandboxed_core:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:

