name: sandboxed_workspace
sdkPath: ".fvm/flutter_sdk"
packages:
  - apps/*
  - packages/*
  - example/*
  - example/monorepo/*

scripts:
  generate:
    exec: fvm dart run build_runner build -d
    packageFilters:
      dependsOn:
      - build_runner

  generate:watch:
    exec: fvm dart run build_runner watch -d
    packageFilters:
      dependsOn:
      - build_runner

  watch_riverpod:
    exec: while true; do dart run build_runner watch -dv; sleep 2 ; done
    packageFilters:
      scope: sandboxed