name: sandboxed_workspace
sdkPath: ".fvm/flutter_sdk"
packages:
  - apps/*
  - packages/*
  - example/*
  - example/monorepo/*

scripts:
  generate:
    exec: fvm dart run build_runner build -d
    # run: fvm dart run build_runner build -d
    # exec:
      # concurrency: 1
    packageFilters:
      dependsOn:
      - build_runner
  watch_riverpod:
    exec: while true; do dart run build_runner watch -dv; sleep 2 ; done
    packageFilters:
      scope: sandboxed