name: vibook
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  vibook_core:

  google_fonts: ^6.0.0
  iconify_flutter_plus: ^1.0.0
  recursive_tree_flutter: ^1.0.0
  flutter_resizable_container: ^4.0.0
  two_dimensional_scrollables: ^0.3.0
  collection: ^1.18.0
  equatable: ^2.0.0

  # riverpod
  flutter_riverpod: ^2.6.0
  riverpod_annotation: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  riverpod_generator: ^2.6.0
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
