name: sandboxed_ui_kit
description: "A reusable component library for the Sandboxed UI development environment. Includes isolated widgets, themes, and layout utilities for rapid prototyping and testing."
version: 0.1.0
homepage: https://sboxed.dev/

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # ui
  flutter_markdown_plus: ^1.0.0
  iconify_flutter_plus: ^1.0.0
  flutter_resizable_container: ^4.0.0
  two_dimensional_scrollables: ^0.3.0

  # core
  markdown: ^7.0.0

  # stories
  faker: ^2.0.0
  sandboxed_core: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

