name: sandboxed_ui_kit
description: "Sandboxed components library"
version: 0.0.1

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # ui
  flutter_markdown_plus: ^1.0.0
  iconify_flutter_plus: ^1.0.0
  flutter_resizable_container: ^4.0.0
  two_dimensional_scrollables: ^0.3.0

  # core
  markdown: ^7.0.0

  # stories
  faker: ^2.0.0
  sandboxed_core:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

