name: sandboxed_test
description: "Reserved package name for future testing utilities related to the Sandboxed UI toolkit."
resolution: workspace
version: 0.0.3
homepage: https://sboxed.dev/

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
