name: vibook_core
description: "ViBook core components"
version: 0.0.1

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  recase: ^4.0.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
