name: sandboxed_core
description: "Core logic and utilities powering the Sandboxed UI development environment. Includes base classes and internal APIs."
resolution: workspace
version: 0.1.2
homepage: https://sboxed.dev/

environment:
  sdk: ">=3.5.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  recase: ^4.0.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
