name: sandboxed_cli
description: CLI tools for the Sandboxed ecosystem to help developers build, test, and showcase widget components in isolation.
resolution: workspace
version: 0.0.2+1
homepage: https://sboxed.dev/
repository: https://github.com/sboxed/sandboxed
issue_tracker: https://github.com/sboxed/sandboxed/issues

environment:
  sdk: ^3.5.4

dependencies:
  args: ^2.5.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
